fetch.py: don't fall with error if no content-type
There are some errors if the run log is empty:
```
Traceback (most recent call last):
  File "./multivac/fetch.py", line 410, in <module>
    job.download_log()
  File "./multivac/fetch.py", line 234, in download_log
    r = http_get(url)
  File "./multivac/fetch.py", line 53, in wrapper
    return http_get_function(*args, **kwargs)
  File "./multivac/fetch.py", line 94, in http_get
    content_type = r.headers['content-type']
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
```
So for now we need to change the method to get header value, so the
script won't fail. Need further work to find why the logs are empty.

Related to #113